project:
  type: book

book:
  title: "STAT765 Assignment"
  subtitle: "Short-Term Forecasting of Net Electricity Consumption for Cohaus"
  author: "Benjamin Preston"
  date: "4/16/2024"
  chapters:
    - index.qmd
    - data.qmd
    - exploration.qmd
    - models.qmd
    - summary.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

