# Data

## Goal

The objective of this project is to produce 3-day forecasts of net energy use for the Cohaus residential development of 20 apartments at 11-13 Surrey Crescent, Grey Lynn, Auckland.

## Data Source

Cohaus was completed in July 2021 and teh community moved in shortly thereafter,, Cohaus has installed solar generation capacity that is applied locally, and if any surplus remains is sold back to the electricity retailer. The data for this project has been collected from the residential development itself (of which the author is an owner-resident). Half hourly kWh electricity use and generation measures are as follows:

-   `APT` aggregated apartment electricity use

-   `CS` common services (lighting, laundry, bike shed, garden house)

-   `EV` electric vehicle chargers

-   `HP` centralised hot water and heat pumps

-   `PV` photo-voltaic electricity generation

Net energy use (i.e. drawn from the grid) is calculated by summing the five measures.

```{r cohaus_data, message=FALSE}

library(tidyverse)
library(readxl)
library(suncalc)
library(fpp3)

# read in cohaus_wide (painful wrangle is in separate wrangle.R)
cohaus_wide <- read_rds("data/cohaus_wide.rds")

# read in nz public holidays (including auckland anniversary)
aklhols <- read_excel("data/aklhols.xlsx") |> 
  mutate(ObsDate = ymd(ObsDate))

# create table of sunrise and sunsets for Auckland, NZ 

Date <- seq(from = floor_date(min(cohaus_wide$dttm)),
            to = floor_date(max(cohaus_wide$dttm)+years(x = 1)),
            by = "day")


getAklSunrise <- function(x = Sys.Date()) {
  tmp <- getSunlightTimes(date = x, 
                           lon = 174.7402, # lon & lat for Grey Lynn
                           lat = -36.8645, 
                           keep = c("sunrise","sunset"), 
                           tz = "Pacific/Auckland"
                          )
  return(as_datetime(tmp[,4]))
}

getAklSunset <- function(x = Sys.Date()) {
  tmp <- getSunlightTimes(date = x, 
                           lon = 174.7402, 
                           lat = -36.8645, 
                           keep = c("sunrise","sunset"), 
                           tz = "Pacific/Auckland"
                          )
  return(as_datetime(tmp[,5]))
}

sunTimes <- tibble(date = Date, 
                   sunrise = getAklSunrise(as_date(Date)),
                   sunset = getAklSunset(as_date(Date))
                   )


# not right needs to be fixed
isSunUp <- function(x = Sys.Date()) {
  ifelse(as_date(x) > getAklSunrise(as_date(x)) & 
         as_date(x) < getAklSunset(as_date(x)), 
         TRUE, FALSE)
}

isSunUp(dmy_hm("18042024 10:00", tz = "Pacific/Auckland"))


# function to determine if workday or not including public hols                   
isWorkDay <- function(x) {
  ifelse(lubridate::wday(x) %in% c(1,7), FALSE, # 1 = Sun, 7 = Sat
         ifelse(x %in% aklhols$ObsDate, FALSE, TRUE))
}

# glom daylight hours and workdays 





```
